"""Comprehensive acceptance tests for US-012: PPT Outline Generation.

Tests are organized by acceptance criteria (AC1-AC4) and verify the
generate_outline() function against the specification in the PrepPackage
model and the PPT outline generator.

Existing basic smoke tests live in test_ppt_outline.py; these tests
build on and extend that coverage without duplicating it.
"""

import pytest

from jarvis.generators.ppt_outline import generate_outline
from jarvis.models.prep_package import PrepPackage, ThreatEvent

# ---------------------------------------------------------------------------
# Helpers / Fixtures
# ---------------------------------------------------------------------------

def _make_threat_event(**overrides) -> ThreatEvent:
    """Create a ThreatEvent with sensible defaults, allowing field overrides."""
    defaults = dict(
        title="LockBit Ransomware Attack",
        date="2026-05-20",
        industry="Manufacturing",
        description="Major manufacturer hit by LockBit ransomware, production halted for 5 days.",
        source_url="https://example.com/threat/lockbit-2026",
    )
    defaults.update(overrides)
    return ThreatEvent(**defaults)


def _make_complete_pkg(**overrides) -> PrepPackage:
    """Create a fully-populated PrepPackage (all 6 modules + threat_intel)."""
    defaults = dict(
        scenario_assessment=(
            "High urgency: customer in manufacturing sector facing active "
            "ransomware campaign targeting their supply chain."
        ),
        sensitivity_alerts=[
            "Avoid mentioning competitor X — they are a current partner.",
            "Budget freeze until Q3 — frame as risk mitigation.",
            "CTO recently joined — may want quick wins.",
        ],
        matched_cases=[
            "manufacturing_ransomware_2025",
            "supply_chain_phishing_2024",
        ],
        follow_up_questions=[
            "What is your current incident response timeline?",
            "Have you evaluated endpoint detection solutions?",
            "Who are the key stakeholders for this decision?",
        ],
        solution_direction=(
            "Deploy EDR across all endpoints; integrate with existing SIEM. "
            "Recommend phased rollout starting with critical production systems."
        ),
        talking_points=(
            "Open with empathy for their situation. "
            "Lead with the cost-of-inaction analysis. "
            "Close with a 30-day pilot proposal."
        ),
        threat_intel=[
            _make_threat_event(),
            _make_threat_event(
                title="Phishing Campaign Targets OEMs",
                date="2026-06-01",
                industry="Automotive",
                description="Spear-phishing campaign targeting automotive OEM procurement teams.",
                source_url="https://example.com/threat/phishing-oem",
            ),
        ],
    )
    defaults.update(overrides)
    return PrepPackage(**defaults)


# ---------------------------------------------------------------------------
# AC1: Complete PrepPackage → 6-page structure
#   Pages: Cover / Industry Landscape / Problem Diagnosis /
#          Solution / Case Reference / Next Steps
# ---------------------------------------------------------------------------

class TestAC1_CompletePackageSixPages:
    """Given a PrepPackage with all 6 modules populated, the outline must
    contain all six pages in the correct order."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.pkg = _make_complete_pkg()
        self.outline = generate_outline(self.pkg)
        self.lines = self.outline.splitlines()

    # -- 1. Cover page -------------------------------------------------------

    def test_cover_page_title_present(self):
        """Cover page must use top-level heading '# Prep Package'."""
        assert "# Prep Package" in self.outline

    def test_cover_page_has_autogen_notice(self):
        """Cover page should include the auto-generated blockquote."""
        assert "> Auto-generated by JARVIS" in self.outline

    # -- 2. Industry Landscape -----------------------------------------------

    def test_industry_landscape_section_present(self):
        assert "## Industry Landscape & Threat Assessment" in self.outline

    def test_industry_landscape_contains_scenario_assessment(self):
        """scenario_assessment content must appear in the Industry Landscape page."""
        assert "High urgency" in self.outline
        assert "ransomware campaign" in self.outline

    # -- 3. Problem Diagnosis ------------------------------------------------

    def test_problem_diagnosis_section_present(self):
        assert "## Problem Diagnosis" in self.outline

    def test_problem_diagnosis_has_sensitivity_subsection(self):
        assert "### Sensitivity Alerts" in self.outline

    def test_problem_diagnosis_lists_all_alerts(self):
        """Every sensitivity_alert must appear as a bullet point."""
        for alert in self.pkg.sensitivity_alerts:
            assert f"- {alert}" in self.outline

    # -- 4. Solution ---------------------------------------------------------

    def test_solution_section_present(self):
        assert "## Solution Direction" in self.outline

    def test_solution_contains_direction_text(self):
        assert "Deploy EDR" in self.outline
        assert "phased rollout" in self.outline

    # -- 5. Case Reference ---------------------------------------------------

    def test_case_reference_section_present(self):
        assert "## Case References" in self.outline

    def test_case_reference_lists_all_cases(self):
        for case_id in self.pkg.matched_cases:
            assert f"- {case_id}" in self.outline

    def test_case_reference_has_followup_subsection(self):
        assert "### Follow-up Questions" in self.outline

    def test_case_reference_lists_all_followup_questions(self):
        for q in self.pkg.follow_up_questions:
            assert f"- {q}" in self.outline

    # -- 6. Next Steps -------------------------------------------------------

    def test_next_steps_section_present(self):
        assert "## Talking Points & Next Steps" in self.outline

    def test_next_steps_contains_talking_points(self):
        assert "Open with empathy" in self.outline
        assert "30-day pilot" in self.outline

    # -- Ordering / structural -----------------------------------------------

    def test_sections_appear_in_correct_order(self):
        """The six page headings must appear in document order."""
        headings = [
            "# Prep Package",
            "## Industry Landscape & Threat Assessment",
            "## Problem Diagnosis",
            "## Solution Direction",
            "## Case References",
            "## Talking Points & Next Steps",
        ]
        positions = [self.outline.index(h) for h in headings]
        assert positions == sorted(positions), (
            "Page sections are not in the expected order"
        )


# ---------------------------------------------------------------------------
# AC2: Empty threat_intel → Industry Landscape page is NOT skipped
#   When threat_intel is empty, the page uses scenario_assessment /
#   sensitivity analysis content and does not disappear.
# ---------------------------------------------------------------------------

class TestAC2_EmptyThreatIntelFallback:
    """Given a PrepPackage with empty threat_intel, the Industry Landscape
    page must still appear with sensitivity-analysis / scenario content."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.pkg = _make_complete_pkg(threat_intel=[])
        self.outline = generate_outline(self.pkg)

    def test_industry_landscape_page_still_present(self):
        """The section heading must exist even when threat_intel is empty."""
        assert "## Industry Landscape & Threat Assessment" in self.outline

    def test_scenario_assessment_content_still_shown(self):
        """scenario_assessment text is the fallback content for this page."""
        assert "High urgency" in self.outline
        assert "ransomware campaign" in self.outline

    def test_recent_threat_events_heading_absent(self):
        """When threat_intel is empty the 'Recent Threat Events' sub-heading
        should NOT appear (there are no events to list)."""
        assert "### Recent Threat Events" not in self.outline

    def test_no_threat_event_bullets(self):
        """No individual threat event bullets should appear."""
        assert "LockBit" not in self.outline
        assert "Phishing Campaign" not in self.outline

    def test_outline_still_has_all_six_pages(self):
        """All other pages must remain intact."""
        for heading in [
            "# Prep Package",
            "## Industry Landscape & Threat Assessment",
            "## Problem Diagnosis",
            "## Solution Direction",
            "## Case References",
            "## Talking Points & Next Steps",
        ]:
            assert heading in self.outline, f"Missing heading: {heading}"


# ---------------------------------------------------------------------------
# AC2 supplement: Populated threat_intel → events appear in output
# ---------------------------------------------------------------------------

class TestAC2_PopulatedThreatIntel:
    """Given a PrepPackage with threat_intel, events must be rendered."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.events = [
            _make_threat_event(),
            _make_threat_event(
                title="Zero-Day in PLC Firmware",
                date="2026-06-10",
                industry="Energy",
                description="Critical zero-day vulnerability discovered in Siemens PLC firmware.",
                source_url=None,
            ),
        ]
        self.pkg = _make_complete_pkg(threat_intel=self.events)
        self.outline = generate_outline(self.pkg)

    def test_recent_threat_events_heading_present(self):
        assert "### Recent Threat Events" in self.outline

    def test_each_event_rendered_as_bullet(self):
        """Each threat event should appear as a Markdown bold-title bullet."""
        for event in self.events:
            expected = f"- **{event.title}** ({event.date}): {event.description}"
            assert expected in self.outline, (
                f"Missing event bullet for: {event.title}"
            )

    def test_event_order_matches_input(self):
        """Events should appear in the same order as the input list."""
        pos_first = self.outline.index("LockBit Ransomware Attack")
        pos_second = self.outline.index("Zero-Day in PLC Firmware")
        assert pos_first < pos_second

    def test_event_with_none_source_url_still_renders(self):
        """source_url=None should not prevent the event from appearing."""
        assert "Zero-Day in PLC Firmware" in self.outline


# ---------------------------------------------------------------------------
# AC3: Standard Markdown hierarchy
#   # page title  /  ## subsection  /  - bullet point
# ---------------------------------------------------------------------------

class TestAC3_MarkdownHierarchy:
    """Verify the outline uses the correct Markdown heading levels and
    bullet-point syntax throughout."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.pkg = _make_complete_pkg()
        self.outline = generate_outline(self.pkg)
        self.lines = self.outline.splitlines()

    def test_top_level_heading_is_cover(self):
        """Exactly one H1 heading: the cover page title."""
        h1_lines = [line for line in self.lines if line.startswith("# ") and not line.startswith("## ")]
        assert len(h1_lines) == 1
        assert h1_lines[0] == "# Prep Package"

    def test_page_titles_use_h2(self):
        """All page-level sections (pages 2-6) use H2 headings."""
        expected_h2 = [
            "## Industry Landscape & Threat Assessment",
            "## Problem Diagnosis",
            "## Solution Direction",
            "## Case References",
            "## Talking Points & Next Steps",
        ]
        for heading in expected_h2:
            assert heading in self.outline, f"Missing H2: {heading}"

    def test_subsections_use_h3(self):
        """Sub-sections within pages use H3 headings."""
        expected_h3 = [
            "### Recent Threat Events",
            "### Sensitivity Alerts",
            "### Follow-up Questions",
        ]
        for heading in expected_h3:
            assert heading in self.outline, f"Missing H3: {heading}"

    def test_bullet_points_use_dash_prefix(self):
        """List items must use '- ' (dash + space) Markdown syntax."""
        bullet_lines = [line for line in self.lines if line.startswith("- ")]
        # We have alerts + cases + follow-ups + threat events = many bullets
        assert len(bullet_lines) >= (
            len(self.pkg.sensitivity_alerts)
            + len(self.pkg.matched_cases)
            + len(self.pkg.follow_up_questions)
            + len(self.pkg.threat_intel)
        )

    def test_no_h4_or_deeper_headings(self):
        """The outline should not use #### or deeper headings."""
        for line in self.lines:
            assert not line.startswith("#### "), (
                f"Unexpected H4+ heading: {line}"
            )

    def test_blockquotes_only_on_cover(self):
        """Blockquote ('>') should only appear on the cover page."""
        bq_lines = [line for line in self.lines if line.startswith(">")]
        assert len(bq_lines) == 1
        assert "Auto-generated by JARVIS" in bq_lines[0]

    def test_threat_event_bullets_use_bold_title(self):
        """Threat event bullets must bold the title: **- title** (...)."""
        for event in self.pkg.threat_intel:
            assert f"**{event.title}**" in self.outline


# ---------------------------------------------------------------------------
# AC4: Missing / empty module fields → outline still generates correctly
#   The page for a module with empty data should still appear (heading)
#   but use fallback content or omit the empty items gracefully.
# ---------------------------------------------------------------------------

class TestAC4_EmptyOrMissingModuleFields:
    """Given a PrepPackage where some module fields are empty/minimal,
    the outline must still generate without errors and include all page
    headings."""

    def test_empty_matched_cases_shows_fallback(self):
        """When matched_cases is empty, a fallback message must appear."""
        pkg = _make_complete_pkg(matched_cases=[])
        outline = generate_outline(pkg)
        assert "## Case References" in outline
        assert "No specific case matches found" in outline

    def test_empty_matched_cases_no_case_bullets(self):
        """No individual case bullets when matched_cases is empty."""
        pkg = _make_complete_pkg(matched_cases=[])
        outline = generate_outline(pkg)
        # Collect only direct bullets under ## Case References
        # (stop at ### Follow-up Questions, which is still within this section)
        in_case_section = False
        case_bullets = []
        for line in outline.splitlines():
            if line == "## Case References":
                in_case_section = True
                continue
            if in_case_section and (line.startswith("## ") or line.startswith("### ")):
                break
            if in_case_section and line.startswith("- "):
                case_bullets.append(line)
        assert len(case_bullets) == 1
        assert "No specific case matches" in case_bullets[0]

    def test_empty_followup_questions_section_still_has_heading(self):
        """Follow-up Questions sub-heading appears even with empty list."""
        pkg = _make_complete_pkg(follow_up_questions=["placeholder"])
        # We cannot use a truly empty list for follow_up_questions without
        # a model change, but we verify the heading exists regardless.
        outline = generate_outline(pkg)
        assert "### Follow-up Questions" in outline

    def test_single_sensitivity_alert_renders(self):
        """Minimum sensitivity_alerts (min_length=1) renders correctly."""
        pkg = _make_complete_pkg(sensitivity_alerts=["Only alert"])
        outline = generate_outline(pkg)
        assert "- Only alert" in outline

    def test_outline_generates_with_all_minimal_valid_fields(self):
        """Outline must generate with the absolute minimum valid PrepPackage."""
        pkg = PrepPackage(
            scenario_assessment="Low urgency",
            sensitivity_alerts=["Single alert"],
            matched_cases=[],
            follow_up_questions=[],
            solution_direction="Monitor and review.",
            talking_points="Keep it brief.",
        )
        outline = generate_outline(pkg)
        # All page headings still present
        assert "# Prep Package" in outline
        assert "## Industry Landscape & Threat Assessment" in outline
        assert "## Problem Diagnosis" in outline
        assert "## Solution Direction" in outline
        assert "## Case References" in outline
        assert "## Talking Points & Next Steps" in outline
        # Fallback content for empty matched_cases
        assert "No specific case matches found" in outline
        # Minimal content still rendered
        assert "Low urgency" in outline
        assert "Monitor and review." in outline
        assert "Keep it brief." in outline
        assert "- Single alert" in outline

    def test_empty_followup_and_cases_together(self):
        """Both matched_cases and follow_up_questions empty at the same time."""
        pkg = PrepPackage(
            scenario_assessment="Standard review",
            sensitivity_alerts=["Watch for budget constraints"],
            matched_cases=[],
            follow_up_questions=[],
            solution_direction="Standard security posture review.",
            talking_points="Focus on relationship building.",
        )
        outline = generate_outline(pkg)
        assert "No specific case matches found" in outline
        assert "## Case References" in outline
        # Follow-up section heading present, but no bullets under it
        assert "### Follow-up Questions" in outline

    def test_multiline_scenario_assessment_renders(self):
        """Multi-line scenario_assessment text should be preserved as-is."""
        assessment = "Line 1: Overview\nLine 2: Details\nLine 3: Recommendation"
        pkg = _make_complete_pkg(scenario_assessment=assessment)
        outline = generate_outline(pkg)
        assert "Line 1: Overview" in outline
        assert "Line 2: Details" in outline
        assert "Line 3: Recommendation" in outline

    def test_outline_is_nonempty_string(self):
        """generate_outline must always return a non-empty string."""
        pkg = _make_complete_pkg()
        outline = generate_outline(pkg)
        assert isinstance(outline, str)
        assert len(outline.strip()) > 0

    def test_no_trailing_whitespace_on_heading_lines(self):
        """Heading lines should not have trailing whitespace."""
        pkg = _make_complete_pkg()
        outline = generate_outline(pkg)
        for line in outline.splitlines():
            if line.startswith("#"):
                assert line == line.rstrip(), (
                    f"Heading has trailing whitespace: '{line}'"
                )
