"""PPT outline generator - converts PrepPackage to structured Markdown outline."""

from jarvis.models.prep_package import PrepPackage


def generate_outline(pkg: PrepPackage) -> str:
    """Generate a PPT-ready Markdown outline from a Prep package.

    Returns a 6-page structured Markdown document:
    1. Cover
    2. Industry Landscape
    3. Problem Diagnosis
    4. Solution
    5. Case Reference
    6. Next Steps
    """
    sections = []

    # Page 1: Cover
    sections.append("# Prep Package\n")
    sections.append(f"> Auto-generated by JARVIS\n")

    # Page 2: Industry Landscape
    sections.append("## Industry Landscape & Threat Assessment\n")
    sections.append(pkg.scenario_assessment)
    sections.append("")

    if pkg.threat_intel:
        sections.append("### Recent Threat Events\n")
        for event in pkg.threat_intel:
            sections.append(f"- **{event.title}** ({event.date}): {event.description}")
        sections.append("")

    # Page 3: Problem Diagnosis
    sections.append("## Problem Diagnosis\n")
    sections.append("### Sensitivity Alerts\n")
    for alert in pkg.sensitivity_alerts:
        sections.append(f"- {alert}")
    sections.append("")

    # Page 4: Solution
    sections.append("## Solution Direction\n")
    sections.append(pkg.solution_direction)
    sections.append("")

    # Page 5: Case Reference
    sections.append("## Case References\n")
    if pkg.matched_cases:
        for case_id in pkg.matched_cases:
            sections.append(f"- {case_id}")
    else:
        sections.append("- No specific case matches found")
    sections.append("")

    sections.append("### Follow-up Questions\n")
    for q in pkg.follow_up_questions:
        sections.append(f"- {q}")
    sections.append("")

    # Page 6: Next Steps
    sections.append("## Talking Points & Next Steps\n")
    sections.append(pkg.talking_points)
    sections.append("")

    return "\n".join(sections)
